"""Builds a double-clickable macOS ``.app`` bundle that launches GUIPlotter.

The bundle is a thin launcher around the *installed* ``guiplotter`` package
rather than a frozen copy of it, so editing the source updates the app without
rebuilding.  That makes it the right tool for a machine you develop on; use
py2app or PyInstaller if you need something to hand to another machine.
"""
from __future__ import annotations

import argparse
import os
import plistlib
import shutil
import subprocess
import sys
import sysconfig
import tempfile
from pathlib import Path

from . import __version__
from .icon import render_iconset

BUNDLE_NAME = "GUIPlotter"
BUNDLE_IDENTIFIER = "io.github.aidancrilly.guiplotter"
DEFAULT_DESTINATION = Path.home() / "Applications"


class BundleError(RuntimeError):
    """Raised when the ``.app`` bundle cannot be assembled."""


def _site_packages() -> list[str]:
    """Returns the import roots of the environment running this build."""

    paths = {sysconfig.get_paths()[key] for key in ("purelib", "platlib")}
    # A src-layout checkout run via ``python -m guiplotter`` is not installed
    # anywhere, so carry the directory the package was actually imported from.
    package_root = str(Path(__file__).resolve().parent.parent)
    paths.add(package_root)
    return [path for path in sorted(paths) if Path(path).is_dir()]


def _build_icon(resources: Path) -> str | None:
    """Renders the icon and converts it to ``.icns``; returns the file name."""

    if not shutil.which("iconutil"):
        return None
    with tempfile.TemporaryDirectory() as workspace:
        iconset = render_iconset(Path(workspace) / f"{BUNDLE_NAME}.iconset")
        icns = resources / f"{BUNDLE_NAME}.icns"
        result = subprocess.run(
            ["iconutil", "--convert", "icns", str(iconset), "--output", str(icns)],
            capture_output=True,
            text=True,
        )
    if result.returncode != 0:
        return None
    return icns.name


def _write_info_plist(contents: Path, icon_file: str | None) -> None:
    info = {
        "CFBundleName": BUNDLE_NAME,
        "CFBundleDisplayName": "GUI Plotter",
        "CFBundleExecutable": BUNDLE_NAME,
        "CFBundleIdentifier": BUNDLE_IDENTIFIER,
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": __version__,
        "CFBundleVersion": __version__,
        "LSMinimumSystemVersion": "11.0",
        "NSHighResolutionCapable": True,
        # Tk owns the window; without this the app cannot take keyboard focus.
        "LSBackgroundOnly": False,
    }
    if icon_file:
        info["CFBundleIconFile"] = icon_file
    (contents / "Info.plist").write_bytes(plistlib.dumps(info))


def _gui_interpreter() -> str:
    """Returns the interpreter binary that can own a macOS GUI session.

    On a python.org framework build ``bin/python3.x`` is only a stub that
    unconditionally re-execs ``Resources/Python.app/Contents/MacOS/Python``.
    That re-exec would replace our bundle identity with Python.app's, so the
    real interpreter behind the stub is what has to go into the bundle.
    """

    gui = Path(sys.base_prefix) / "Resources" / "Python.app" / "Contents" / "MacOS" / "Python"
    if gui.is_file():
        return str(gui)
    return os.path.realpath(sys.executable)


def _embed_interpreter(macos: Path) -> str:
    """Copies the interpreter into the bundle and returns a shell-quoted path.

    macOS derives an app's Dock name and icon from the path of the running
    executable, so the interpreter is copied inside the bundle where that path
    walks back up to ``GUIPlotter.app``.  Copying invalidates the interpreter's
    code signature, hence the ad-hoc re-sign; relocatable standalone builds may
    still refuse to run from the copy, so the result is verified before use.
    """

    original = _gui_interpreter()
    embedded = macos / "python"
    try:
        shutil.copy2(original, embedded)
    except OSError:
        return f'"{original}"'

    if shutil.which("codesign"):
        subprocess.run(
            ["codesign", "--force", "--sign", "-", str(embedded)],
            capture_output=True,
            text=True,
        )

    probe = subprocess.run(
        [str(embedded), "-c", "import tkinter"],
        capture_output=True,
        text=True,
        env={**os.environ, "PYTHONHOME": sys.base_prefix},
    )
    if probe.returncode != 0:
        embedded.unlink(missing_ok=True)
        return f'"{original}"'
    return f'"$BUNDLE_MACOS/{embedded.name}"'


def _write_launcher(macos: Path, interpreter: str) -> None:
    python_path = os.pathsep.join(_site_packages())
    launcher = macos / BUNDLE_NAME
    launcher.write_text(
        "#!/bin/sh\n"
        "# Generated by `guiplotter-make-app`; rebuild it after moving the\n"
        "# Python environment this app was created from.\n"
        'BUNDLE_MACOS=$(cd "$(dirname "$0")" && pwd)\n'
        f'PYTHONHOME="{sys.base_prefix}"\n'
        f'PYTHONPATH="{python_path}${{PYTHONPATH:+{os.pathsep}$PYTHONPATH}}"\n'
        "export PYTHONHOME PYTHONPATH\n"
        f"exec {interpreter} -m guiplotter \"$@\"\n"
    )
    launcher.chmod(0o755)


def build_app(destination: Path = DEFAULT_DESTINATION, *, force: bool = False) -> Path:
    """Creates ``<destination>/GUIPlotter.app`` and returns its path."""

    if sys.platform != "darwin":
        raise BundleError("macOS app bundles can only be built on macOS.")

    app = destination / f"{BUNDLE_NAME}.app"
    if app.exists():
        if not force:
            raise BundleError(f"{app} already exists; pass --force to replace it.")
        shutil.rmtree(app)

    contents = app / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    _write_info_plist(contents, _build_icon(resources))
    _write_launcher(macos, _embed_interpreter(macos))

    # Ad-hoc signing keeps Gatekeeper and the Dock from treating the freshly
    # assembled bundle as damaged.
    if shutil.which("codesign"):
        subprocess.run(
            ["codesign", "--force", "--deep", "--sign", "-", str(app)],
            capture_output=True,
            text=True,
        )
    # Nudge Launch Services so the app is searchable straight away.
    subprocess.run(["touch", str(app)], capture_output=True)
    return app


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="guiplotter-make-app",
        description="Build a GUIPlotter.app bundle you can keep in the Dock.",
    )
    parser.add_argument(
        "--destination",
        type=Path,
        default=DEFAULT_DESTINATION,
        help=f"directory to create the bundle in (default: {DEFAULT_DESTINATION})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace an existing bundle at the destination",
    )
    args = parser.parse_args(argv)

    args.destination.mkdir(parents=True, exist_ok=True)
    try:
        app = build_app(args.destination, force=args.force)
    except BundleError as error:
        parser.exit(1, f"error: {error}\n")

    print(f"Created {app}")
    print("Open it once from Finder, then right-click its Dock icon to Keep in Dock.")
    return 0


__all__ = ["BundleError", "build_app", "main"]
